// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQxi35d2yS4ulvb35ugPVZdK-drsee94',
    appId: '1:380849449877:web:04ce668c0db0aaf30fe49c',
    messagingSenderId: '380849449877',
    projectId: 'examinate-5d8d3',
    authDomain: 'examinate-5d8d3.firebaseapp.com',
    databaseURL: 'https://examinate-5d8d3-default-rtdb.firebaseio.com',
    storageBucket: 'examinate-5d8d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wVN4_kbS-a6NcyvoriGsSHQsunK-CNE',
    appId: '1:380849449877:android:0444aae1a24745730fe49c',
    messagingSenderId: '380849449877',
    projectId: 'examinate-5d8d3',
    databaseURL: 'https://examinate-5d8d3-default-rtdb.firebaseio.com',
    storageBucket: 'examinate-5d8d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UFbifsnTPb1UhAtKVCb_RXvbvcnab0o',
    appId: '1:380849449877:ios:4504aa1f93e07bf00fe49c',
    messagingSenderId: '380849449877',
    projectId: 'examinate-5d8d3',
    databaseURL: 'https://examinate-5d8d3-default-rtdb.firebaseio.com',
    storageBucket: 'examinate-5d8d3.appspot.com',
    iosBundleId: 'com.example.examinate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UFbifsnTPb1UhAtKVCb_RXvbvcnab0o',
    appId: '1:380849449877:ios:4504aa1f93e07bf00fe49c',
    messagingSenderId: '380849449877',
    projectId: 'examinate-5d8d3',
    databaseURL: 'https://examinate-5d8d3-default-rtdb.firebaseio.com',
    storageBucket: 'examinate-5d8d3.appspot.com',
    iosBundleId: 'com.example.examinate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMQxi35d2yS4ulvb35ugPVZdK-drsee94',
    appId: '1:380849449877:web:2dfced2656f7e3aa0fe49c',
    messagingSenderId: '380849449877',
    projectId: 'examinate-5d8d3',
    authDomain: 'examinate-5d8d3.firebaseapp.com',
    databaseURL: 'https://examinate-5d8d3-default-rtdb.firebaseio.com',
    storageBucket: 'examinate-5d8d3.appspot.com',
  );
}
